# Generated by Django 5.2.16 on 2026-09-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("cid", models.IntegerField(primary_key=True, serialize=False)),
                ("cname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Capital",
            fields=[
                ("capId", models.IntegerField(primary_key=True, serialize=False)),
                ("capName", models.CharField(max_length=100)),
                (
                    "cid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.country"
                    ),
                ),
            ],
        ),
    ]
