# Generated by Django 5.2.16 on 2026-09-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=100, unique=True)),
                ("loc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SalGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField()),
                ("losal", models.FloatField()),
                ("hisal", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("mgr", models.IntegerField()),
                ("hiredate", models.DateField()),
                ("sal", models.FloatField()),
                ("comm", models.FloatField()),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.dept"
                    ),
                ),
            ],
        ),
    ]
