# Generated by Django 5.2.16 on 2026-09-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="comm",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="emp",
            name="hiredate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="emp",
            name="mgr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.emp",
            ),
        ),
        migrations.AlterField(
            model_name="emp",
            name="sal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="salgrade",
            name="hisal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="salgrade",
            name="losal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
