# Generated by Django 5.2.16 on 2026-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_emp_comm_alter_emp_hiredate_alter_emp_mgr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salgrade",
            name="id",
        ),
        migrations.AlterField(
            model_name="emp",
            name="comm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salgrade",
            name="grade",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
