# Generated by Django 5.2.16 on 2026-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
