# Generated by Django 5.2.16 on 2026-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_webpage_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="mobile",
            field=models.CharField(default="1234567890", max_length=10),
            preserve_default=False,
        ),
    ]
