# Generated by Django 5.2.16 on 2026-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_webpage_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrecord",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
